version: 2.1
commands:
  early_return_for_forked_pull_requests:
    description: >-
      If this build is from a fork, stop executing the current job and return success.
      This is useful to avoid steps that will fail due to missing credentials.
    steps:
      - run:
          name: Early return if this build is from a forked PR
          command: |
            if [ -n "$CIRCLE_PR_NUMBER" ]; then
              echo "Nothing to do for forked PRs, so marking this step successful"
              circleci step halt
            fi

executors:
  linux-8-jdk:
    docker:
      - image: cimg/openjdk:8.0

jobs:
  build:
    parameters:
      os:
        type: executor

    executor: << parameters.os >>

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - jedis-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: jedis-{{ checksum "pom.xml" }}

      - run: |
          sudo apt update
          sudo apt install -y stunnel

      - run: |
          sudo apt-get install ca-certificates curl gnupg lsb-release
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt update
          sudo apt install -y docker-ce docker-ce-cli containerd.io

      - run: make circleci-install

      - run: TEST="" make test

      - early_return_for_forked_pull_requests

      - run: bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN}

      - run: mvn -s .circleci.settings.xml -DskipTests deploy

workflows:
  all-jdks:
    jobs:
      - build:
          matrix:
            parameters:
              os: [linux-8-jdk]
