version: 2.1

executors:
  linux-8-jdk:
    docker:
      - image: circleci/openjdk:8-jdk
  linux-7-jdk:
    docker:
      - image: circleci/openjdk:7-jdk

jobs:
  build:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - restore_cache:
          keys:
            - jedis-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline 
      - save_cache:
          paths:
            - ~/.m2
          key: jedis-{{ checksum "pom.xml" }}

      - run: |
          sudo add-apt-repository ppa:redislabs/redis
          sudo apt update
          sudo apt install -y stunnel redis

      - run: TEST="\!ModuleTest" make test

  build-nightly:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - restore_cache:
          keys:
            - jedis-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline 
      - save_cache:
          paths:
            - ~/.m2
          key: jedis-{{ checksum "pom.xml" }}

      - run: |
          sudo apt update
          sudo apt install -y stunnel

      # Nightly is tested with Redis unstable
      - run: make circleci-install
      - run: TEST="\!ModuleTest" make test

workflows:
  all-jdks:
    jobs:
      - build:
          matrix:
            parameters:
#              os: [linux-8-jdk, linux-7-jdk]
              os: [linux-8-jdk]
  all-jdks-nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build_nightly:
          matrix:
            parameters:
#              os: [linux-8-jdk, linux-7-jdk]
              os: [linux-8-jdk]

