name: Documentation Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  doctests:
    runs-on: ubuntu-latest
    services:
      redis-stack:
        image: redis/redis-stack-server:latest
        options: >=
          --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            /var/cache/apt
          key: jedis-${{hashFiles('**/pom.xml')}}

      # modify me
      #- name: build and run tests
      #  run: |
      #    mvn compile -DskipTests
      #    mvn ...
