name: CI

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**/*.rst'
      - '**/*.md'
    branches:
      - master
      - '[0-9].[0-9]'
  pull_request:
    branches:
      - master
      - '[0-9].[0-9]'

jobs:

  test_modules:
    runs-on: ubuntu-latest
    name: Test Modules
    steps:
      - uses: addnab/docker-run-action@v3
        with:
          image: redislabs/redismod:edge
          options: --name mod -p 6379:6379

      - uses: actions/checkout@v2
      - name: Set up publishing to maven central
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: maven cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            /var/cache/apt/repository
          key: jedis-${{ hashFiles('**/pom.xml') }}
      - name: sync offline dependencies
        run: mvn dependency:go-offline
      - name: build and test
        run: mvn -DmodulesDocker="mod:6379" -Dtest="redis.clients.jedis.modules.**" test

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: [test_modules]
    steps:
      - uses: actions/checkout@v2
      - name: Set up publishing to maven central
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: maven cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            /var/cache/apt/repository
          key: jedis-${{ hashFiles('**/pom.xml') }}
      - name: sync offline dependencies
        run: mvn dependency:go-offline
      - name: install dependencies
        run: |
          sudo apt update -q
          sudo apt install -yq stunnel make
      - name: get ip
        id: get_internal_ip
        run: |
          IP=`ip -4 -o address show dev eth0|awk '{print $4}'|cut -d '/' -f 1-1`
          echo "::set-output name=INTERNALIP::${IP}"
      - name: build redis
        run: make circleci-install SENTINELMASTER=${{steps.get_internal_ip.outputs.INTERNALIP}}
      - name: run tests
        run: TEST="" make test
      - name: publish snapshot
        run: mvn --no-transfer-process --batch-mode -DskipTests deploy
        if: github.event_name != 'pull_request'
      - name: Upload codecov coverage
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
