---

name: Integration

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
      - '**/*.rst'
    branches:
      - master
      - '[0-9].*'
  pull_request:
    branches:
      - master
      - '[0-9].*'
  schedule:
    - cron: '0 1 * * *' # nightly build
  workflow_dispatch:

jobs:

  build:
    name: Build and Test - Redis Stack ${{matrix.redis-stack-version}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        redis-stack-version: ['6.2.6-v12', '7.2.0-v8', 'edge']
    env:
      REDIS_STACK_VERSION: ${{matrix.redis-stack-version}}
    steps:
      - uses: actions/checkout@v4
      - name: Set up publishing to maven central
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            /var/cache/apt
          key: jedis-${{hashFiles('**/pom.xml')}}
      - name: Maven offline
        run: |
          mvn -q dependency:go-offline
      - name: Build docs
        run: |
          mvn javadoc:jar
      - name: Run tests
        run: |
          make test
        env:
          JVM_OPTS: -Xmx3200m
          TERM: dumb
      - name: Codecov
        run: |
          bash <(curl -s https://codecov.io/bash)
